spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/drone
    username: root
    password: password
    platform: mysql
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        type: trace
